# Generated by Django 4.2 on 2024-12-17 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(500)]),
        ),
        migrations.AlterField(
            model_name='report',
            name='reason',
            field=models.CharField(blank=True, choices=[('spam', 'Spam or misleading'), ('inappropriate', 'Inappropriate content'), ('fraud', 'Fraud or scam'), ('other', 'Other')], max_length=50),
        ),
    ]
